services:
  - type: web
    name: link-tracker
    env: python
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn app:app --config gunicorn_config.py --timeout 1800 --workers 2 --threads 4 --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: link-tracker-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: link-tracker-db
    databaseName: link_tracker
    user: link_tracker_user
    plan: free
